FIX - should now work with php8.1 (not fully tested...)
PHProxy/phproxy pull request #29
Opened 2022-10-24 08:51 UTC by dacendo

2022-11-13 20:29 UTC, snowykittens commented
Fixes the url entry page completely but something still goes wrong when attempting to proxify an address

2025-08-21 21:46 UTC, Quix0r requested changes

2025-08-21 21:46 UTC, Quix0r commented on index.php
> +
Please delete these extra empty lines.

2026-05-27 21:06 UTC, miglen commented
Thanks for the patch — your null-trim casts for HTTP_REFERER, response header parsing, and cookie-domain handling were incorporated into #48 with credit as a co-author. The wider PHP 8.5 modernization is now on master. Closing in favor of #48.

2026-05-27 21:06 UTC, closed without merging